# Site
name: 'The Lore Blog'
description: 'The global education and learning blog #LearningNeverEnds'
meta_description: 'The global education and learning blog #LearningNeverEnds'
logo: 'assets/images/lore-logo-r.svg'
favicon: 'assets/images/lore-logo-r.svg'
google_analytics: 'UA-124640434-3'
lore_url: 'https://lore.online'

# Authors
authors:
  kavita:
    name: Kavita
    display_name: Kavita Mehta
    description: Kavita Mehta is a thought leader at the intersection of education, skill-building, technology and impact. Her 25-year career across financial services, digital media and entrepreneurship is firmly grounded in her belief that education is a right, not a privilege. Her focus on mentorship empowers others to magnify impact and increase confidence through a keen awareness of their own potential. She is the founder of Caymus Technology Ventures, co-founder of The Red Pen and author of Acing Admissions, published by HarperCollins.
    image: '/assets/images/authors/kavita-mehta.jpg'
    profile: https://www.linkedin.com/in/kavitamehta01
  educationdive:
    name: educationdive
    display_name: Educationdive
    description: Education Dive provides news and analysis for higher ed and k-12 leaders. We cover topics like online learning, policy, ed tech,  MOOCs, admissions, blended learning and more.
    image: '/assets/images/authors/education-dive.svg'
    profile: https://www.educationdive.com
  kavita-namita:
    name: Kavita & Namita
    display_name: Kavita Mehta & Namita Mehta
    description: Kavita Mehta is a thought leader at the intersection of education, skill-building, technology and impact. Her 25-year career across financial services, digital media and entrepreneurship is firmly grounded in her belief that education is a right, not a privilege. She is the founder of Caymus Technology Ventures, co-founder of The Red Pen and author of Acing Admissions, published by HarperCollins. For this article, Kavita joined forces with Namita Mehta, who currently serves as the President of The Red Pen and who had earlier established and run the university counseling department at BD Somani International School in Mumbai. The co-authors offer their unique yet diverse perspectives to parents and other stakeholders deciphering the global education landscape.
    image: '/assets/images/authors/kavita-namita.png'
  anshul:
    name: Anshul
    display_name: Anshul Tripathi
    description: Anshul Tripathi is a third-year student at the University of Pennsylvania. Originally from Mumbai, Anshul spends his time on campus working as a teaching assistant, focused on helping his juniors find their footing in computer science or helping international students understand the nuances of American English.
    image: '/assets/images/authors/anshul.jpeg'
    profile: https://www.linkedin.com/in/anshultripathi2699/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge
